/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konversi_suhuku;

/**
 *
 * @author yogi
 */
public class suhu extends javax.swing.JFrame {

    /**
     * Creates new form suhu
     */
    public suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        celcius = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fahrenheit = new javax.swing.JRadioButton();
        calvin = new javax.swing.JRadioButton();
        Celcius = new javax.swing.JRadioButton();
        Fahrenheit = new javax.swing.JRadioButton();
        Calvin = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        konversi = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        popup1 = new conversi_suhu2.popup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI KONVERSI SUHU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 19, 250, 71));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jLabel2.setText("INPUT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 133, 66, 26));

        celcius.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        celcius.setText("Celcius");
        celcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celciusActionPerformed(evt);
            }
        });
        getContentPane().add(celcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 226, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("FROM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 201, 66, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("TO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 191, 63, 33));

        fahrenheit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fahrenheit.setText("Fahrenheit");
        getContentPane().add(fahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 252, -1, -1));

        calvin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calvin.setText("Calvin");
        getContentPane().add(calvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 278, -1, -1));

        Celcius.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Celcius.setText("Celcius");
        getContentPane().add(Celcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 226, -1, -1));

        Fahrenheit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Fahrenheit.setText("Fahrenheit");
        Fahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FahrenheitActionPerformed(evt);
            }
        });
        getContentPane().add(Fahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 252, -1, -1));

        Calvin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Calvin.setText("Calvin");
        getContentPane().add(Calvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 278, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Result");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 415, 77, 35));
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 415, 286, 36));

        konversi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        konversi.setText("CALCULATE!");
        konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiActionPerformed(evt);
            }
        });
        getContentPane().add(konversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 333, 142, 38));

        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 333, 82, 38));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 333, 76, 38));

        jLabel6.setText("@riantikinasih");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 473, -1, -1));

        popup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup1ActionPerformed(evt);
            }
        });
        getContentPane().add(popup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 124, 339, 44));

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void celciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celciusActionPerformed

    private void FahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FahrenheitActionPerformed

    private void konversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiActionPerformed
        // TODO add your handling code here:
    double hasil1;
    double suhu = Double.parseDouble(popup1.getText());
    
        if (popup1.getText().isEmpty()) {
           
        } else {
            try {
                if (celcius.isSelected() && Celcius.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil.setText(String.valueOf(suhu));
                    
                } else if (celcius.isSelected() && Fahrenheit.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil1 = suhu * 1.8 + 32;
                    hasil.setText(String.valueOf(hasil1));
                    
                } else if (celcius.isSelected() && Calvin.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil1 = suhu + 273.15;
                    hasil.setText(String.valueOf(hasil1));
                    
                } else if (fahrenheit.isSelected() && Celcius.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil1 = (suhu - 32) / 1.8;
                    hasil.setText(String.valueOf(hasil1));
                    
                } else if (fahrenheit.isSelected() && Fahrenheit.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil.setText(String.valueOf(suhu));
                   
                } else if (fahrenheit.isSelected() && Calvin.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil1 = (suhu + 459.67) / 1.8;
                    hasil.setText(String.valueOf(hasil1));
                    
                } else if (calvin.isSelected() && Celcius.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil1 = suhu - 273.15;
                    hasil.setText(String.valueOf(hasil1));
                    
                } else if (calvin.isSelected() && Fahrenheit.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil1 = suhu * 1.8 - 459.67;
                    hasil.setText(String.valueOf(hasil1));
                    
                } else if (calvin.isSelected() && Calvin.isSelected()) {
                    suhu = Double.parseDouble(popup1.getText());
                    hasil.setText(String.valueOf(suhu));                 
                }
            } catch (NumberFormatException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_konversiActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        popup1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void popup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popup1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new suhu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Calvin;
    private javax.swing.JRadioButton Celcius;
    private javax.swing.JRadioButton Fahrenheit;
    private javax.swing.JRadioButton calvin;
    private javax.swing.JRadioButton celcius;
    private javax.swing.JButton clear;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton fahrenheit;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton konversi;
    private conversi_suhu2.popup popup1;
    // End of variables declaration//GEN-END:variables
}
